global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus自身の監視
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Go アプリケーションの監視
  - job_name: 'go-app'
    static_configs:
      - targets: ['go-app:8080']
    metrics_path: '/api/metrics'
    scrape_interval: 30s

  # Python AIサービスの監視
  - job_name: 'python-ai'
    static_configs:
      - targets: ['python-ai:8001']
    metrics_path: '/ai/metrics'
    scrape_interval: 30s

  # Node Exporter（システムメトリクス）
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
